### ISSUE TITLE
Gradient Mixin Enhancements

### ISSUE THREAD

**Issue by ajmueller** [connectivedx/Phoenix#107]
Now that we have the ability to use Sass maps, we can enhance our gradient mixin pretty easily.  Some possibilities:

- multiple color stops
- direction choice
- radial gradient (perhaps better served as a separate mixin?)

Dependent on work in #105.

Thoughts?

**Comment by ajmueller** [comment]
Here's a nice blog post by Hugo Giraudel about building a solid gradient mixin: http://www.sitepoint.com/building-linear-gradient-mixin-sass/

**Comment by elseloop** [comment]
Work included in #159 covers multiple color stops and optional directions. After some internal discussions, we’re opting to hold off radial gradient support until need or desire necessitate it. Provided there are no objections or better ideas, when #159 is merged in, it will close both this and #156. Any radial-gradient requests/work can happen under an additional issue/feature branch as a stand-alone mixin (as @ajmueller parenthetically suggested in opening this issue).

Thoughts?

**Comment by elseloop** [comment]
Closing now that #159 is in master.
