### ISSUE TITLE
Decorator Select Overflow

### ISSUE THREAD

**Issue by ajmueller** [connectivedx/Phoenix#128]
On a recent project a Marketo form's validation message was being hidden because the `.decorator-select` class has `overflow: hidden` set on it.  This seems like an unnecessary property to set; its only other purpose that I can see is to clip the decorator's arrow image, but that image should just be cropped to be the correct height for your inputs anyway.

**Comment by stoff** [comment]
I think this is legacy from something that I was doing when I originally created decorator select using pointer-events. I don't recall the details, just that I needed it for some reason.  kill it, please.

**Comment by elseloop** [comment]
“kill it, please” is how all bug reports should end!
![](http://i.giphy.com/wvFrJa4aWKuvm.gif)
