### ISSUE TITLE
Adding ES5 Shim for better Array functions support

### ISSUE THREAD

**Issue by chadian** [connectivedx/Phoenix#135]
There tends to pop up a few situations where using array methods would be nice without having to use jQuery's helpers. The jQuery helpers don't allow you to chain the array functions since it expects the array as a parameter. Most browsers have these natively built in, it's only for support with IE8 I believe. If IE8 support is being dropped sooner than later, then I believe there's no point in adding this. 

Issue to drop IE8 Support:
https://github.com/connectivedx/Phoenix/issues/83

ES5 Shim to add prototype extensions to Arrays (and a few others):
https://github.com/es-shims/es5-shim

**Comment by ajmueller** [comment]
I was discussing this recently with Jiro and @stoff and I discuss it somewhat often.  In the next couple months I would imagine we'd have a release that removes IE8 support.  The official end of life of IE8 will be in January and new SOWs that we sign will begin to remove IE8 support very soon (in fact, it's already begun).  Ideally we would completely drop IE8 support from master and refer anyone who needs IE8 support to an older release; if bug fixes are needed in the IE8 release, we can have an IE8 support branch that we maintain for a bit.

**Comment by chadian** [comment]
Cheers to that, I suppose this can be closed then and I'll just avoid using some of these methods for a few more months.

**Comment by ajmueller** [comment]
I don't see anything wrong with relying on these methods and shims when you need to; we did that with Panoptes recently.  It just might not be necessary for the main Phoenix project as part of the default build.
