### ISSUE TITLE
Gradient mixin has no direction option

### ISSUE THREAD

**Issue by devinrayolsen** [connectivedx/Phoenix#156]
Our gradient mixin does not have any options to set the direction of the gradient. I've made a new branch "feature/gradient-directions" that now extends a third optional param for direction.

You can use either the four keywords of top, left, bottom and right (with fall-back of bottom), or numerical 45deg values.

Thoughts?

**Comment by elseloop** [comment]
:+1: 

My only note would be to put the new direction parameter into an options map in keeping with the conventions we've got in other mixins. See [aspect-ratio](https://github.com/connectivedx/Phoenix/blob/master/Assets/src/css/mixins/_aspect-ratio.scss#L17-L20) for an example.

**Comment by devinrayolsen** [comment]
![Roger](http://memecrunch.com/meme/19LA5/roger-that/image.png)

Updated.

**Comment by elseloop** [comment]
Can you open a PR with your feature branch against `development`, please?

**Comment by elseloop** [comment]
Fixed by #159
