### ISSUE TITLE
Review templates with PHP set to report errors (dev mode)

### ISSUE THREAD

**Issue by stoff** [connectivedx/Phoenix#167]
I'm seeing a couple of notices on the grid-system-test.php template which are only visible to me because I have my local PHP instance set to dev mode.  This issue is in addition to the issue reported in #166.

I'd like it if we could make some time to thoroughly review all PHP functionality for errors - I would hate to have integration on a PHP stack blocked because of an error Phoenix is producing.

**Comment by elseloop** [comment]
Yeah, I'm seeing `Notice: Undefined offset: -1` in a couple places in `grid-system-test.php`. Assuming we can write around this with a couple `array_key_exists` checks.

Looking at logs and reviewing the defaults, these and the notices you reported in #166 are the only PHP errors I'm seeing.

**Comment by elseloop** [comment]
Fixed by #171
