### ISSUE TITLE
Update columns mixin to prevent @extend being called within @media rules

### ISSUE THREAD

**Issue by stoff** [connectivedx/Phoenix#193]
The column mixin previously changed to remove the arbitrary breakpoint, and is now used (almost) exclusively within `@media` rules.  It still contains two `@extend` directives, however, which are not permitted within `@media` rules.  The extends can be seen in [mixins/grid/_semantic-grid.scss](https://github.com/connectivedx/Phoenix/blob/master/Assets/src/css/mixins/grid/_semantic-grid.scss) on [line 88](https://github.com/connectivedx/Phoenix/blob/master/Assets/src/css/mixins/grid/_semantic-grid.scss#L88) and [line 76](https://github.com/connectivedx/Phoenix/blob/master/Assets/src/css/mixins/grid/_semantic-grid.scss#L76).

I'd recommend removing both extend rules and inserting the css:
```
	float: $defaultFloat;
	margin: 0;
	min-height: 1px;
```
 from `%column-config` directly before the logic block in the mixin.

**Comment by elseloop** [comment]
Fixed in 2.2.4
